[alias]
clippy-all = ["clippy", "--all-features", "--all-targets", "--tests", "--workspace", "--quiet"]
coverage = [
  "llvm-cov",
  "test",
  "--lib",
  "--all-features",
  "--branch",
  "--json",
  "--summary-only",
  "--output-path",
  "target/coverage/unit.json",
  "--fail-uncovered-lines",
  "0",
  "--fail-uncovered-regions",
  "0",
  "--fail-uncovered-functions",
  "0",
  "--",
  "--skip",
  "proptests",
]
coverage-proptests = [
  "llvm-cov",
  "test",
  "--lib",
  "--all-features",
  "--branch",
  "--json",
  "--output-path",
  "target/coverage/proptests.json",
  "--",
  "proptests",
]
deny-check = ["deny", "check"]
fmt-all = ["fmt", "--all"]
fmt-check-all = ["fmt", "--all", "--check"]
mutants-all = ["mutants"]
test-workspace = ["test", "--workspace", "--all-features"]
test-all = [
  "nextest",
  "run",
  "--all-features",
  "--workspace",
  "--cargo-quiet",
  "--show-progress",
  "none",
  "--status-level",
  "fail",
  "--final-status-level",
  "fail",
  "--success-output",
  "never",
]
test-doc = ["test", "--doc", "--all-features", "--workspace"]

[build]
rustflags = [
  "--deny",
  "unsafe_code",
  "--deny",
  "warnings",
]

[deny]
config = ".cargo/deny.toml"

[env]
CLIPPY_CONF_DIR = { value = ".cargo", relative = true }
MACOSX_DEPLOYMENT_TARGET = "26.0"
